# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sandbox',
                'doc_host': 'https://jakubjecha.github.io',
                'git_url': 'https://github.com/jakubjecha/sandbox',
                'lib_path': 'sandbox'},
  'syms': { 'sandbox.core': {'sandbox.core.foo': ('core.html#foo', 'sandbox/core.py')},
            'sandbox.sandbox_main': {'sandbox.sandbox_main.foo': ('sandbox_main.html#foo', 'sandbox/sandbox_main.py')}}}
